### ISSUE TITLE
parseYoutubeResults throws useless fatal error if any exception other than BadResponseException is thrown

### ISSUE THREAD

**Issue by blendermf** [t2t2/mc-site#2]
I was testing the youtube data update command, and I had my curl settings configured incorrectly, but I couldn't see it's complaint because that promise was throwing a RequestException, and not a BadResponseException that it only currently handles. It should probably have a more general Exception handler, as well as the more specific BadResponseException one.

**Comment by t2t2** [comment]
Originally I was gonna say that it shouldn't matter as it should check the typehint and if it doesn't match the reject method gets skipped (and original excpetion gets forwarded)....

but looks like it's only happening on [use of otherwise](https://github.com/reactphp/promise/blob/f2b2a127557e1236fe95aaa3288b49ae6b9b3c45/src/Promise.php#L59). Changed to use it (which now that I've had ages to work with js promises shoulda done so)

Aside: if upgrade guzzle 5 -> 6 need to make the function if instanceof .... else throw $error as it's promises implementation doesn't support typehints

But, that being said it should now forward the exception as-is and it should show up?

**Comment by blendermf** [comment]
Yes, I can confirm it now forwards the exception correctly.
