### ISSUE TITLE
Calendar: Time (Local time calculation)

### ISSUE THREAD

**Issue by t2t2** [t2t2/mc-site#8]
Ooof, the true third circle of hell - time & zones

So there's gonna be 2 types of events: Where the local time is more important (conventions, physical events), and where user's time is more important (online), and the hybrid of both (it's 1.5th, not 3rd). (see #7)

So as an upgrade:
- Adding timezone field type, using http://php.net/manual/en/datetimezone.listidentifiers.php to source the values
- Adding choice of which time displays to prefer (local/both/user)
- Adding user side calculation:
  - http://momentjs.com/timezone/
  - Use frontend code like follow to indicate use (can be targeted with `$("[data-local-time]").map`:  
    `<time data-local-time="text" data-time="2013-11-18 11:55" data-zone="America/Los_Angeles"></time>`
    - local-time: text/title -> where to calcuate the local time (text for when you want to show it on page, title for extra hover convenience calculation (maybe if it's set to show just local time)
    - time: Time
    - zone: Location (so DST can properly be calculated)
    - (optional?) format?

Possible outputs depending on setting:
- (local) When? October 4th, 2016 @ 01:09pm  
  hover: October 4th, 2016 @ 01:09pm
- (both) When? October 4th, 2016 @ 01:09pm (October 4th, 2016 @ 09:09pm in your time)
- (user) When? October 4th, 2016 @ 09:09pm in your time

(appendum: switch to 24h :^) )

**Comment by blendermf** [comment]
That all seems very sensible (and way less clunky than what I added, and more useful).

(I did actually look into using moment.js, but then got lazy thinking about the backend part of things)

**Comment by blendermf** [comment]
On my local setup I created that has a timezone field type (with a slightly modified select field template that removes options that are unnecessary, like multiple selections, or values). Right now because of the relative simplicity of the way fields are implemented, I added a constructor for the field that takes the app, and then adds a global for the timezones, like this:

``` php
public function __construct(Application $app) {
    $app['twig']->addGlobal('timezones', timezone_identifiers_list());
}
```

and then I just changed the add field call to 

``` php
$config->getFields()->addField(new TimeZoneField($app));
```

It works well enough(I haven't noticed it break anything), but I don't really know if it's a great solution. Previously I just had the global being added in registerCustomFields under SiteServiceProvider.php, but I feel like putting that in the field class makes more sense. If this is fine I'll just commit this though.

[EDIT] Screw it, just added what I did with 3a1e861, feel free to make it better if you feel the need. Doesn't really matter as long as it spits out the same values.

**Comment by blendermf** [comment]
One issue I've just thought of, if users are in a timezone where it's another day (which in turn could mean month or year), do we try to modify the day / month in some way (on pages like the calendar / the front page where, month, year and day are all kind of in different areas grouped and ordered in certain ways). Maybe just assume the chosen time zone for the front page, and on the calendar use the chosen time zone, but if it's set to local, show the full date (with month / day / year) with the details; and if set to both show just the time from the chosen one, and the full thing in the brackets or  however that's displayed.

**Comment by blendermf** [comment]
Added all the server side template stuff to support this for the single event template as of 1543219
Also in addition to what you described, I added the event time to the title of the time element when it's set to show the user time, because why not. It's also showing timezone abbreviations in the times now too.
On to the calendar template.
And then actually adding the moment.js client-side logic. I'll probably just wait until we switch over to webpack before I do that (assuming we do that).

**Comment by blendermf** [comment]
Should we support events that don't display the time? Like I'm thinking for some kind of all day(/multiday) event? Or would it be best just to have them put the start time there (and if needed go into more detail in the body).

EDIT: Implemented the server side template changes for the calendar listing template with b513baa

**Comment by t2t2** [comment]
Hmmm yeah just leave it as start time

**Comment by t2t2** [comment]
![mc-local-times](https://cloud.githubusercontent.com/assets/1122555/14697522/317f4646-078d-11e6-92b9-9e7b5b8baf90.png)

Should be mostly good now, whatever touchups you can find to do (Also using UTC was able to avoid using moment-timezone, and probably can cut down on the extra package by removing some moment localisations?)

**Comment by blendermf** [comment]
Modified things so that on event pages, the full date will be shown(in both the converted times when needed, and the local event times) as of 18c0615
